### ISSUE TITLE
Milestone #2: Script for EDA

### ISSUE THREAD

**Issue by hatefr** [UBC-MDS/forest-fire-area-prediction-group-2#27]
Hi everyone, I kinda re-did EDA for the classification problem. I have included the jupyter notebook for that (labelled EDA_classification). I also wrote a script which reads in the preprocessed data and output two images: one for number of fire occurrences for different seasons and one showing the pair plot for all numerical columns. Feel free to use them in the final report. Also Let me now if you want to output more plots.

**Comment by Anahita97** [comment]
We also considered classification for our project, however, ended up using regression at the end.
